name: Deploy to Firebase Hosting on push

# Trigger on pushes to main branch
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - uses: actions/checkout@v3

      # 2. Set up Node.js (adjust version if needed)
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build your site (adjust if your command differs)
      - run: npm run build

      # 5. Deploy to Firebase Hosting
      - uses: w9jds/firebase-action@v1
      with:
    args: deploy --only hosting
      env:
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
