name: Deploy to Firebase Hosting on push

# Trigger on pushes to main
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the site
      - name: Build
        run: npm run build

      # 5. Deploy to Firebase Hosting
      - name: Deploy
        uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
